# Generated by Django 6.1.1 on 2026-09-26 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='swipee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipe',
            name='swiper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='swipe',
            unique_together={('swiper', 'swipee')},
        ),
    ]
